######################## default configuration ####################
baseURL = "/"
languageCode = "en-us"
title = "Cognizant Netcentric Open Source"
theme = "influencer-hugo"
summaryLength = "10"
paginate = 10

ignoreErrors = ["error-remote-getjson"]

[markup.goldmark.renderer]
unsafe= true

[caches]
[caches.getjson]
dir = ":cacheDir/:project"
maxAge = "10s"

############################# Plugins ##############################
[params.plugins]

############################## navigation ###############################
[menu]

  [[menu.main]]
  name = "Projects"
  URL = "https://github.com/orgs/Netcentric/repositories"
  weight = 1

  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight = 2

  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 3

  [[menu.main]]
  name = "Code of Conduct"
  URL = "code-of-conduct"
  weight = 4

#################### default parameters ################################
[params]
logo = "images/netcentric-logo.svg"
home = "Home"
# Meta data
description = "At Cognizant Netcentric we value open source and encourage everyone internally and externally to contribute to our projects..."
author = "Themefisher"
[params.copyright]
  text = "Cognizant Netcentric"
  link = "https://www.netcentric.biz/"

[params.social]
  twitter = "https://twitter.com/NetcentricHQ"
  linkedin = "https://www.linkedin.com/company/netcentric-a-cognizant-digital-business/"

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Navigation get start button
[params.navButton]
enable = false

############################# post share ###################
[[params.share]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.share]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.share]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.share]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "#"