name: Build Site

on:
  push:
    branches:
      - main
  schedule:
      - cron: "0 0 * * 1"

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install dependencies
        run: npm ci
      - name: Build Hugo
        uses: chabad360/hugo-gh-pages@master
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}